### ISSUE TITLE
GOTHiChicup wrong help

### ISSUE THREAD

**Issue by NicolasH2** [borimifsud/GOTHiC#1]
I think the help for GOTHiChicup is incorrect. It says that the input table should contain only the read ID, chromosome, start and end positions columns. This does not work however, and going into the function code I saw that the input should rather be ID, flag, chromosome, locus (found in the .importHicup function, lines 475,478,487 & 490 (https://github.com/borimifsud/GOTHiC/blob/master/R/GOTHiC.R). After changing the input file accordingly there were no problems.

**Comment by borimifsud** [comment]
Thank you, that is correct. I have now fixed it.
